### ISSUE TITLE
lstm model not so straightforward to implement

### ISSUE THREAD

**Issue by miccio-dk** [Christie22/SingleChannelDenoising#2]
not  much literature on denoising autoencoders with lstm layers:
- https://mediatum.ub.tum.de/doc/1253789/file.pdf
- ...???

as opposed to those using conv layers:
- https://arxiv.org/abs/1703.08019
- https://arxiv.org/abs/1811.02938
- https://github.com/senior-sigan/denoise-autoencoder

should we just downscale temporarely? :thinking:

**Comment by Christie22** [comment]
Indeed, this doc wasn't very helpful! you can find a better explanation of LSTMs in part 2.4.3 (Recurrent Neural Networks and LSTMs) of the overview [1] that Lars and Ulrik sent us. I really like this documentary, it is well explained in general :)
[1]: Single-Channel Speech Enhancement using Deep Learning, Hulser, 2018

For the concept of LSTM, these 2 documents [18,19] seem to be references (I haven't looked into them though, but they were cited in [2]):
[2] Discriminatively Trained Recurrent Neural Networks for Single-Channel Speech Separation
[18]S. Hochreiter and J. Schmidhuber, “Long short-term memory,” Neural Computation, vol. 9, no. 8, pp. 1735–1780, 1997.
[19] F. Gers, J. Schmidhuber, and F. Cummins, “Learning to forget: Continual
prediction with LSTM,” Neural Computation, vol. 12, no. 10, pp. 2451–
2471, 2000.

And to complete the picture, this one: [20]. Doesn't bring much explanation, but uses LSTM for speech separation. And cites [2].
[20]: PHASE-SENSITIVE AND RECOGNITION-BOOSTED SPEECH SEPARATION USING DEEP RECURRENT NEURAL NETWORKS, 2015, Erdogan

I hope it helps

**Comment by Christie22** [comment]
A tuto that looks good:
https://adventuresinmachinelearning.com/keras-lstm-tutorial/

**Comment by miccio-dk** [comment]
thanks for the resources, i'll give it another try today :)

**Comment by miccio-dk** [comment]
good source for lstm NOT applied to text: https://github.com/keras-team/keras/blob/master/examples/conv_lstm.py

**Comment by miccio-dk** [comment]
lol nvm
